apiVersion: v1
kind: Service
metadata:
  name: wil42-playground
spec:
  type: LoadBalancer
  selector:
    app: wil42-playground
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
  
